### ISSUE TITLE
Rewarded Issue close activity.

### ISSUE THREAD

**Issue by SagareGanesh** [joshsoftware/code-curiosity#101]
For eg. Issue [derrek/street-address#35](https://github.com/derrek/street-address/issues/35) which I had opened on 23 Aug was rewarded that time. 
Thats correct, But when I closed this Issue its rewarded again :flushed: 
Is this behavior correct?
Thoughts?

**Comment by SagareGanesh** [comment]
I have investigated, why Issue close activity rewarded. :blush: 
---
In current system we only considers two type of activity, which are _**IssueActivity**_ and _**IssueCommentActivity**_. And Issue close activity is under _**IssueActivity**_ type. we are not considering the action of activity.

I ll happy to create PR, just let me know.

**Comment by BandanaPandey** [comment]
Thanks @SagareGanesh , we will be grateful if you can create PR for this.

**Comment by SagareGanesh** [comment]
Hi @BandanaPandey, 
I think we don't need to create seperate _**PR**_ for this, because @prasadsurase  has already resolved this issue in his [PR](https://github.com/joshsoftware/code-curiosity/pull/109). so I close this issue.  _**Thanks**_ @prasadsurase.

**Comment by SagareGanesh** [comment]
This issue is not resolved yet.

**Comment by prasadsurase** [comment]
@SagareGanesh This issue is resolved but not deployed.

**Comment by BandanaPandey** [comment]
@SagareGanesh this is deployed. So please close it.
