### ISSUE TITLE
Documentation required.

### ISSUE THREAD

**Issue by prasadsurase** [joshsoftware/code-curiosity#105]
The critical modules of the application source need documentation. eg, modifying the [Scoring Engine](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/scoring_engine.rb) to fix this [bug](https://github.com/joshsoftware/code-curiosity/issues/101) is problematic since no docs are present. The documents can help us create [rdocs](https://github.com/rdoc/rdoc) for the repo.

**Comment by gautamrege** [comment]
Agreed. We need to get cracking on this. I would recommend opening the Github Wiki to contribute.

**Comment by wyhaines** [comment]
At this point, the docs are what the docs are.

I am closing this and will add documentation as I can while figuring things out and working on things.
