### ISSUE TITLE
Open-source activities should not only limited to Github. blogs, talks and other code sources should be considered.

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/code-curiosity#107]
Open source is not limited to sending pull request or opening issue. Writing blogs, Talks at conference / Meetups and stackoverflow are also ways of contributing to open source.

Can we fetch data of
- Blogs from feed url entered by user (We need to trust user enters correct url or admin need to verify that)
- Conference / Meetup talks Video/ Presentation links (user need to enter this manually)
- Stackoverflow points (By connecting StackOverflow account to code curiosity)

We might not be able to do automated judging for blogs and talks but we can assign some badge to user based on number of talks and blogs. 

If we do this CodeCuriosity will be place where user can see his entire open source contribution graph.

**Comment by gautamrege** [comment]
Excellent idea. @SagareGanesh had started something around StackOverflow integration but I have still to see it. This is **definitely** on the cards and shall be done once we have a little more bandwidth.


* Cross promotion of codetriage and docsdoctor as this is a great starting point for open-source involvement. 
* I also want to initiate integration into Codeclimate to evaluate code smell and score it! 
* Integration with StackOverflow, Lanyard, Papercall (even submitting a CFP is great effort - it keeps conferences going), slideshare, etc. 
* Blogs can be updated in CodeCuriosity Profile and should help -- but we need to exercise caution for potential mis-use.

FYI - most if this can be auto-scored!

**Comment by gautamrege** [comment]
Consolidating information in the description and renaming this ticket to understand this feature better.

**Comment by wyhaines** [comment]
Closing this because while the idea is sound, implementation is problematic, and is not in the schedule for the next couple of months.
