### ISSUE TITLE
Does CodeCuriosity really need organizations and teams access while authorizing application?

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/code-curiosity#108]
While authorizing application CodeCuriosity asks user to give access to organizations and teams.
![permissions](https://cloud.githubusercontent.com/assets/6301532/18359313/06068a4e-7617-11e6-994d-78e67b6b2dfc.png)

CodeCuriosity really don't care about private data at all. If user has made his organization as public we can fetch data from github handle.

For ex. I don't have any public organization so none will be listed though I am member of some organizations and @anuja-joshi is member has couple of public organizations so those we can fetch from API without her access token

```
31] pry(main)> Github::Client::Orgs.new.list(user: 'anuja-joshi').count
=> 2
```

If user don't make organization as public it means he don't want that data to be shown anywhere.

People might have concern while signing up that CodeCuriosity will see my private organizations as well.

**Comment by gautamrege** [comment]
Yes - we have seen this issues. It would really help if you can submit a validated PR on this.  If we fire queries to Github API without a an auth-token, we get quickly rate-limited. So, we need auth-tokens to get information. Earlier, we were using the registered users authtoken to get a list of repos and org repos. Hence we need the permission.

However, we changed this as we started hitting the rate-limits. Now, we can use any auth-token available and this helps us get over the rate limiting. So, NOW, we may not need this Orgs permission. 
So you may be right.. however, we need to test it out thoroughly. 

Also, we need to tell users that they  need to make their Organisation Public visible if they want us to evaluate the code there for CodeCuriosity.

**Comment by Shwetakale** [comment]
@gautamrege Yes will submit PR for this shortly.

**Comment by Shwetakale** [comment]
@gautamrege I tried this but there is no way to handle this we need to have organization permissions as we can't query github with ```access_token``` to get organizations of user withought orgs permissions.

We can query github withought ```access_token``` but that has limit of 60 requests per hour which won't be feasible for us. If we setup association between repository and organization and try to send minimum queries to github still we will be able to refresh only 10 users per hour by considering user will have 5 public organizations. 

So I think this issue can be closed.
