### ISSUE TITLE
Should user's gists be considered?

### ISSUE THREAD

**Issue by prasadsurase** [joshsoftware/code-curiosity#110]

**Comment by gautamrege** [comment]
A little more thought is required on this.

The problem currently is that you cannot browse a users Gists (at least I have not found a way to do so) unless the Gist is shared. This means that I can keep copy-pasting code in various gists and CodeCuriosity will pick it up an score it -- opens the door for potential mis-use. 

Also, in my opinion, gists are small snippets of code that people use to share a problem, a solution but it's not big enough for collaboration (though gists can be forked etc..) Hence, IMO, we should **not** consider gists. 

A community discussion around this an the +1 pressure for this feature request with  clear road-map would be great.  If we find strong reasons for adding gists without it being mis-used we shall do so.

**Comment by wyhaines** [comment]
Closing. There is no reason currently to add scoring of gists.
