### ISSUE TITLE
Throws error when we click on dashboard featured groups

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#114]
![issue](https://cloud.githubusercontent.com/assets/280199/18410965/461b7ba6-778b-11e6-914c-51e45e7ae982.png)

**Comment by Shwetakale** [comment]
@sivagollapalli This is when you are not signed in into code curiosity. When you are signed in into codecuriosity you will see user's profile page but it is always showing logged in user's graph.

**Comment by sivagollapalli** [comment]
@Shwetakale Then disable the click for the users who are not logged in would solve the issue? Make sense?

**Comment by prasadsurase** [comment]
Unable to reproduce the error on live app. All the users listed on the home page are viewable without signing-in to the application.

**Comment by sivagollapalli** [comment]
@prasadsurase looks like the issue has been fixed. @BandanaPandey Could you please confirm?
