### ISSUE TITLE
Are trend charts at https://codecuriosity.org/trend working?

### ISSUE THREAD

**Issue by spidergears** [joshsoftware/code-curiosity#116]
Trends for all categories are downwards.... Are they setup correctly? Also Y-axis has points, what's in X-axis? Days of month? 

![screen shot 2016-09-14 at 11 29 52 am](https://cloud.githubusercontent.com/assets/3817081/18501508/ac76fe26-7a6e-11e6-95a1-fc19c000f0e6.png)
![screen shot 2016-09-14 at 11 30 00 am](https://cloud.githubusercontent.com/assets/3817081/18501509/ac77c1ee-7a6e-11e6-99df-f6fa8c0204db.png)
![screen shot 2016-09-14 at 11 30 11 am](https://cloud.githubusercontent.com/assets/3817081/18501510/ac797674-7a6e-11e6-8e75-39b1bb26f163.png)

**Comment by BandanaPandey** [comment]
@spidergears yes trends are correct, this graph is showing you the number of users and there corresponding points for the current round (in your case Sep) and corresponding goal(Hiker, Mountaineer, Rover).
Y-axis have points whereas x-axis have tickInterval of one corresponding to that of y where plotting is done as mentioned in [points_chart.js](https://github.com/joshsoftware/code-curiosity/blob/master/app/assets/javascripts/points_chart.js)

**Comment by spidergears** [comment]
@BandanaPandey Okay, got it. It's a Points vs UserCount graph. Consider adding a label to X-axis.
