### ISSUE TITLE
Hide `Points will be credited to your account by the end of the month` text

### ISSUE THREAD

**Issue by spidergears** [joshsoftware/code-curiosity#117]
Text should only be visible to signed in users on their own profile only.

![screen shot 2016-09-14 at 11 35 15 am](https://cloud.githubusercontent.com/assets/3817081/18501608/6970edde-7a6f-11e6-9450-8a3fdec1a576.png)

**Comment by BandanaPandey** [comment]
#120  fixed it, now text 'Points will be credited to your account by the end of the month' will be visible to only signed-in users

**Comment by gautamrege** [comment]
Fixed and will be deployed.
