### ISSUE TITLE
"Teams" page should be seen without authentication

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#12]
Everyone should be able to see the teams and the repositories that the team is working on.

Currently, we have to inform the team by email about changes. It should be quite clear from DAY-1 of the round. Also, it's important that the teams see what others are working on.

* The "bs-callout (green / red / orange), Active From and Actions should NOT be shown without login. 
* You cannot create new teams without logging in.

FYI - you can remove the "Active From" column entirely - the Round has the dates in it.

**Comment by kirandc** [comment]
Closed in 39aaba3
