### ISSUE TITLE
[suggestion] Scope the dashboard view to month?

### ISSUE THREAD

**Issue by nixmaniack** [joshsoftware/code-curiosity#124]
Current dashboard shows overall accumulated activity counts but clicking on any of the `Points`, `Commits` or `Activity` gives scoped details for the current selected month. It would make more sense to show the scoped dashboard and have an entry in "Month" selection to see overall view.

**Comment by gautamrege** [comment]
Hmm.. Considering the recent changes we have made for adding Trends, I wonder if the "profile" and the "dashboard" are now the same. The Profile shows the points distribution scoped over various months as a chart as well as a table and the overall points are visible on the left side-pane.  What do you think? 

@sethu thoughts?

**Comment by nixmaniack** [comment]
> The Profile shows the points distribution scoped over various months as a chart as well as a table and the overall points are visible on the left side-pane.

Hadn't checked this. This looks nice and covers the case of looking at points scoped over months. Thanks for this addition. (May be you should have a blog post or some changelog  whenever new changes/features are pushed? :) ) 

Although, clicking on dashboard widgets still remains a bad UX from my perspective as it gives scoped view when clicked on them rather than showing overall detailed view.
