### ISSUE TITLE
Branch merge commits getting scored

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/code-curiosity#127]
When we take latest pull from base repo and resolves conflict that merge commit is also scored. See screenshot below.

Should this commit get scored? While going through code I observed [here](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/repository.rb#L140) is check for "pull request merge" commit. Should there be same check for "Branch merge commit" ?

![codecuriosity](https://cloud.githubusercontent.com/assets/6301532/18607534/73b2c068-7cec-11e6-8dea-587d58970bce.png)

**Comment by Shwetakale** [comment]
In the same context of scoring [here](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/scoring_engine.rb#L91) there is a check if sum of commit_score,comment_score and bugspot_score is 0 then that commit should be scored as 1. This might be to ensure each commit get scored (minimum 1). But what if sum of above 3 scores come to 0 to 0.49 then round value will be 0 and then that commit will be scored 0. Thoughts?

**Comment by anilmaurya** [comment]
Ideally you should not pull from base repo instead you should rebase your branch with base branch.

Although if you like to pull instead of rebasing then you should squash merge commits before sending pull request.

**Comment by Shwetakale** [comment]
@anilmaurya Thanks Yes I should have done rebase but I didn't. But anyone can do mistake like I have done so it's good to have that check as well. Thoughts?
