### ISSUE TITLE
Test Coverage!

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#13]
We need to get test coverage completed for Code-Curiosity - we need to practice what we preach!

**Comment by spatil** [comment]
Yes. I will take repos, members & teams

**Comment by spatil** [comment]
there is already minitest included in Gemfile. Lets continue with that.

**Comment by SagareGanesh** [comment]
I have completed test cases for 2 models ( Comment and Goal ).

**Comment by wyhaines** [comment]
Closing.  This will be reassessed as part of getting Code Curiosity back into production shape.
