### ISSUE TITLE
Unable to set existing goal for next month

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/code-curiosity#130]
See attached screenshot I had set next month goal as Mountainer but now I want to change it to Hiker but CodeCuriosity doesn't seem to be allow that

![codecuriosity](https://cloud.githubusercontent.com/assets/6301532/18698784/801eea6a-7fea-11e6-8fc1-6fbc58c30fe9.png)

**Comment by BandanaPandey** [comment]
@Shwetakale once you have set goal you cannot change it, for the current month, because of this you are not able to change your goal from Mountainer to Hiker.
You can refer this [set_goal](https://github.com/joshsoftware/code-curiosity/blob/master/app/controllers/users_controller.rb)

**Comment by anilmaurya** [comment]
I also want to change my Goal 👍

**Comment by nixmaniack** [comment]
@BandanaPandey But as the OP says, you should be able to set current goal (in OPs case `Hiker`) as **next month's** goal. The issue over here is, once you select next month's goal as `Mountaineer` or `Rover` there's no way to set that back to `Hiker`. 

> once you have set goal you cannot change it, for the current month, because of this you are not able to change your goal from Mountainer to Hiker.

For the **next** month, we should be able to set it as Hiker - which is not possible in current UI. 

P.S. I accidentally set it as `Rover` for next month now I'm not able to set it as `Hiker`!

**Comment by Shwetakale** [comment]
@BandanaPandey Agreed I cannot change month for current month but If I select any other goal it is applied for next month. Now I have selected 'Montaneer' and it is showing it has been set for next month but now I want my next month's Goal to be 'Hiker' but I am not able to do that and in next month I won't be able to change as we can't change for current month.

**Comment by Shwetakale** [comment]
@BandanaPandey Also on UI I think it should be documented that if should give alert before selecting a goal that it will be applicable for next month and not for current month.

**Comment by SagareGanesh** [comment]
@Shwetakale @BandanaPandey I think we should able to change our current goal also, Because at start of month or before start of month we can not decide how much time we will get in future for open source.
So it will be better if we add this option.
thoughts?
thanks.

**Comment by Shwetakale** [comment]
@SagareGanesh No I think we should not allow this because think about the case if at the start of month I set goal as 'Mountanineer' and in that month I only get 20 points then just to get the bonus point I will change it to 'Hiker' which should not be allowed and yes reverse can also happen :)

 So it should be like set a goal if you achieve goal you will get bonus points else not and for achieving the same people will try to do as much open source as they can.

**Comment by SagareGanesh** [comment]
@Shwetakale  Yes you are _**right**_, this will be happen, But In that case there will be restriction on only _**degradation**_ of goal not on _**upgradation**_. Is there any _**disadvantages**_ in upgradation of current month goal? 
thoughts?
thanks

**Comment by Shwetakale** [comment]
@SagareGanesh Yes agreed user should be able to upgrade his goal but not be allowed to degrade.

**Comment by prasadsurase** [comment]
IMO downgrading or upgrading a goal should be permitted only in the first few days(say, 5 days) of the round. Also, when downgrading a goal, user should not be assigned the bonus points.

**Comment by BandanaPandey** [comment]
@prasadsurase I agree that user should be allowed to upgrade or degrade their goal only at the beginning of the month .
This will help in setting the next month goal at the beginning of the next month even though it has been set accidentally.

**Comment by SagareGanesh** [comment]
@BandanaPandey I think, If we give an option to change the current month goal( only for first few days) , then there is no need to give an option for next month. Because It will automatically resolve an issue of setting or changing next month goal.
thanks.

**Comment by gautamrege** [comment]
This was thought through earlier -- there is never a good time to change the goal. Hence, we decided that when you change the goal, it will be set as next month's goal. So, I believe, we should allow you to change the goal anytime and any number of times in the month but it will take effect only from the next month onwards.

Hope this resolves everyone issues.

**Comment by SagareGanesh** [comment]
@gautamrege thanks, Can we just update the set goal button label _**Set as Goal**_ to  _**Set Goal for Next Month**_, so it will be more descriptive. 
![goal](https://cloud.githubusercontent.com/assets/16730632/18836024/bf3b9308-841b-11e6-88fc-b1b100fb11a7.png)

**Comment by budhrg** [comment]
> This was thought through earlier -- there is never a good time to change the goal

@gautamrege I am really interested to know what kind of issues it will bring if we allow to change current's month goal any time.

One use case where one need is, suppose, one set the next month goal as **Mountaineer**, current month passed, next month comes with **Mountaineer** as goal, 1 week passed, earned 10 points, next two weeks due to emergency user got out of coding, last week he could earn max 20 points. Then, he couldn't achieve the bonus points. But if he had set the goal as **Hiker**, he could have got 20 bonus points. 
This allows users to behave smartly here.

Any thoughts?
