### ISSUE TITLE
Sign In to GitHub page shows Gautam's photo instead of Code Curiosity logo

### ISSUE THREAD

**Issue by Lakshmi-Sharma** [joshsoftware/code-curiosity#135]

**Comment by budhrg** [comment]
Interesting :smile:

**Comment by Shwetakale** [comment]
@Lakshmi-Sharma It seems to be if owner of application don't upload logo for application then Github by  default sets is to the profile picture of application owner.

**Comment by gautamrege** [comment]
Busted 😄 Fixed.
