### ISSUE TITLE
Inconsistency in date format.

### ISSUE THREAD

**Issue by SagareGanesh** [joshsoftware/code-curiosity#138]
Currently on _**Activities**_ and _**Commits**_ page we are using _**dd/mm/yy**_ date format. But I noticed on _**Points History**_ page its _**mm/dd/yy**_.  Which format do we want to use? so user will not get confused.
I will send PR after confirmation.

**Comment by prasadsurase** [comment]
IMO we should use the Github date format(say, Sept 30 2016).

**Comment by BandanaPandey** [comment]
Fixed in this [commit](https://github.com/joshsoftware/code-curiosity/pull/137/commits/b29d1426785046f8c424aa8ecaa664db773e1069).

**Comment by SagareGanesh** [comment]
Thanks @BandanaPandey.
