### ISSUE TITLE
Scoring PR Review Comments as Activity

### ISSUE THREAD

**Issue by adityashedge** [joshsoftware/code-curiosity#139]
AFAIK PR comments are not considered as Activity in Code Curiosity(correct me if I'm wrong).
It is possible to pull out the Review Comments on pull request using [this](https://developer.github.com/v3/pulls/comments/) API.

P.S. The rules for scoring Review Comments should not same as Issue comments because PR comments will be shorter comparatively. So to start off, we can only score those Review Comments which have `code` blocks.

**Comment by nixmaniack** [comment]
I had raised a similar issue at #122. It's now discussed in #91

**Comment by adityashedge** [comment]
I would say keep Review Comments as a separate issue where we can discuss the logic.
But you can close this issue as a duplicate of #91, as suggested by @gautamrege in #122 
Thank you @nixmaniack for pointing this out.
