### ISSUE TITLE
Status: "In review" for commits from a long time

### ISSUE THREAD

**Issue by Princu7** [joshsoftware/code-curiosity#165]
I don't know whether this is the appropriate place for this type of queries. So pardon me if it isn't and redirect me to the right place.  Anyway, I really like the concept of code curiosity and it has given me the motivation to contribute to the open source.
I have made several commits this month.But most of them are still showing the status "In review" from a very long time(some commits were made almost 10 days ago) and no points have been awarded on them. Also some commits fetch no points which is a little disheartening considering they also required some effort to make.

Here is the screenshot showing the status
![screenshot from 2016-10-16 15-41-09](https://cloud.githubusercontent.com/assets/8847265/19416794/5c148a18-93b7-11e6-8b56-a8b064bc7f8a.png)

I kindly request someone to please look into this issue. I would also love to know the scoring logic and how points are distributed to the various commits. Thanks for your time.

**Comment by gautamrege** [comment]
@Princu7 I shall check why the 5-Oct commits are in "in review". Thanks for the ticket.

The automated scoring algorithm is being improved as we learn more code patterns and usage. So, hang in there - it will start getting better!

**Comment by Princu7** [comment]
@gautamrege  Thank you so much for your time. Are there any docs  which state how the scoring is done currently? I tried to read the source code but was not successful as I am unfamiliar with ruby.  I would love to suggest an idea or two.

**Comment by prasadsurase** [comment]
@Princu7 The [whenever schedule](https://github.com/joshsoftware/code-curiosity/blob/master/config/schedule.rb#L28) file calls a rake task daily which triggers autoscoring. The [task](https://github.com/joshsoftware/code-curiosity/blob/master/lib/tasks/auto_score.rake#L7) calls  [ScoringJob](https://github.com/joshsoftware/code-curiosity/blob/master/app/jobs/scoring_job.rb). All the scoring logic is in [ScoringEngine](https://github.com/joshsoftware/code-curiosity/blob/master/app/models/scoring_engine.rb#L89). We use [bugspot](https://github.com/igrigorik/bugspots) as a major component for scoring. You can refer [this](https://github.com/joshsoftware/code-curiosity/issues/129) issue to discuss about changes needed in scoring logic.

**Comment by Shwetakale** [comment]
This might be because of [this issue] (https://github.com/joshsoftware/code-curiosity/pull/128) .

**Comment by gautamrege** [comment]
@Shwetakale No - this is not related. 

@Princu7 - please check the issue is resolved. I think there may be a clash between parallel 'git pull'. we are seeing if that is indeed the case and will resolve. 

re-open is you still see issues.
