### ISSUE TITLE
Typo in FAQ page

### ISSUE THREAD

**Issue by vivganes** [joshsoftware/code-curiosity#166]
The word `Mozilla` is misspelt in https://codecuriosity.org/faq

`Mozzila` needs to be corrected as `Mozilla`.

I was looking for faq page in the repo to contribute a PR. Couldnt find it.  I can raise a PR if someone can point me to the source of faq page.

**Comment by prasadsurase** [comment]
@vivganes The faqs are retrieved from [config/info.yml](https://github.com/joshsoftware/code-curiosity/blob/master/config/info.yml).

**Comment by sethu** [comment]
It has been fixed in the master branch and the deployment is pending. It will be deployed ASAP.
