### ISSUE TITLE
Mismatch in activity/commit data across screens

### ISSUE THREAD

**Issue by vivganes** [joshsoftware/code-curiosity#168]
Until this afternoon, I was able to see my activities for this month correctly.  But, now, I get a message "There are no commits".

However, the chart shows right data.

Here are screenshots.

![screen shot 2016-10-18 at 4 36 39 pm](https://cloud.githubusercontent.com/assets/2035886/19475356/54755832-9551-11e6-8293-b5bf65b09c02.png)

![screen shot 2016-10-18 at 4 37 14 pm](https://cloud.githubusercontent.com/assets/2035886/19475364/5df41bfa-9551-11e6-9127-d67b61f83464.png)

![screen shot 2016-10-18 at 4 37 20 pm](https://cloud.githubusercontent.com/assets/2035886/19475368/64853eae-9551-11e6-9e11-f7ad864ffca8.png)

**Comment by prasadsurase** [comment]
@vivganes The Commits and Activities tab display the related data as per the selected month(month on the top right side, left side of user profile pic). IMO, you might have selected some old month, data for which is absent.

**Comment by vivganes** [comment]
@prasadsurase  Thanks! My bad! The top month selection was `August 2016` which was the problem.  I must have changed it sometime ago and left it that way.

When I changed to current month `October 2016` , I am seeing the right data.
