### ISSUE TITLE
Individual Metrics  for scores, commits and activities.

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#17]
In addition to team metrics, we should have individual metrics -- by Rounds.

**Comment by anilmaurya** [comment]
Can we have metrics for overall scores, commits and activities ?

**Comment by gautamrege** [comment]
@anilmaurya This is the title of this issue is :smile: Did you mean average scores for each commit, score and activity?

**Comment by anilmaurya** [comment]
No, I meant individual metrics -- Overall .

It show overall commit, score, activity till last round.

For example:

If 2 rounds are completed than it will show metrics combining results of both rounds.

**Comment by gautamrege** [comment]
I would recommend that we see the graph just like we see the "Team Scores" today. 

Instead of the team name, it will be the contributor name. Instead of the individual splits of the team members, we show the numbers for 5 rounds details.  There will be separate graphs for commits, activity and scores. 

More ideas on this welcome.

**Comment by anilmaurya** [comment]
If we can get graph like bonusly , it will be great 


![screen shot 2015-11-27 at 3 47 35 pm](https://cloud.githubusercontent.com/assets/1912864/11438970/63db0fbc-951e-11e5-8a55-eaefd1c2569a.png)


Filter by rounds on this graph will be nice.
