### ISSUE TITLE
Sudden drop in points

### ISSUE THREAD

**Issue by redfast00** [joshsoftware/code-curiosity#172]
First of all: thank you for this awesome service. It motivates me to contribute to opensource projects.

I used to have ~20 points, and all of a sudden it dropped to 9 points. If I manually count the yellow squares in the activities menu, I get to 21 (probably my old score). Does this mean that some contibutions don't count anymore? Thanks a lot!

**Comment by redfast00** [comment]
Okay, I checked it out and it seems only my commits are counted: no issues, comments,...

**Comment by gautamrege** [comment]
Issues and comments are scored under Contributions -> "Activities". I can see them scored and up-to-date.. Please specify some particular details, so that we can resolve it.

**Comment by redfast00** [comment]
![screenshot_20161020-154459](https://cloud.githubusercontent.com/assets/10746993/19562366/5426ad72-96dc-11e6-8261-319daf382516.png)
If I count the points under activities, I get to 21.

**Comment by Princu7** [comment]
I can confirm this issue. I used to have ~25 points but not it has dropped to 11.

**Comment by gautamrege** [comment]
@Princu7 @redfast00 -- yes there is some regression problem -- working on it.

**Comment by budhrg** [comment]
In my case, the points droped from 11 to 2 
![screenshot from 2016-10-24 15-37-40](https://cloud.githubusercontent.com/assets/1132451/19641793/f59857fc-99ff-11e6-8f1c-34ab33954048.png)
