### ISSUE TITLE
Activities and commits not being counter after 16 Oct

### ISSUE THREAD

**Issue by Princu7** [joshsoftware/code-curiosity#177]
Thanks to @gautamrege   for solving the previous issue related to the incorrect updation of the points and status of the commits . I am sorry to trouble with another issue. It seems like none of my activities and commits made after the 16 Oct are being shown. I made around 2-3 commits and several comments during this period all in a repository satisfying the required criteria but still they are not being tracked. Here are the screenshots 

![screenshot from 2016-10-24 20-08-45](https://cloud.githubusercontent.com/assets/8847265/19650108/bb08121e-9a25-11e6-813e-52ffe1dac561.png)
![screenshot from 2016-10-24 20-08-51](https://cloud.githubusercontent.com/assets/8847265/19650121/c5f9c820-9a25-11e6-95d2-37fc25bbd3e6.png)

Kindly look into this matter. Thanks.

**Comment by gautamrege** [comment]
@Princu7 This has been addressed -- the regression bug impacted this too. It's been resolved and the server is updating all commits and activities currently. You should see your commits and activities updated within a couple of hours. 

Check back tomorrow and re-open this ticket in case you don't see this shortly.
