### ISSUE TITLE
homepage is not reponsive

### ISSUE THREAD

**Issue by arpit1997** [joshsoftware/code-curiosity#180]
when homepage is opened on small screens like smartphones it looks like below:
![image](https://cloud.githubusercontent.com/assets/10682054/19686003/f5644bbe-9adc-11e6-9bb1-bc65720fa386.png)

Try to make it responsive :+1:

**Comment by gautamkrishnar** [comment]
Alsp the settings pages:
![tmp_14416-screenshot_20170209-041545963291835](https://cloud.githubusercontent.com/assets/8397274/22761018/fc6cdec6-ee7e-11e6-8f55-9dfacb5fc67f.png)
![tmp_14416-screenshot_20170209-041534-689839119](https://cloud.githubusercontent.com/assets/8397274/22761032/0e891868-ee7f-11e6-8db6-e1e4adb85994.png)

**Comment by gautamkrishnar** [comment]
I think you should just kerp tje setting tabs in the Left hamburger menu. Make a single menu vlef settings and male it collapsible with all the options..

**Comment by amitk** [comment]
@arpit1997 As this issue is fixed please close this issue.
