### ISSUE TITLE
It is possible to maliciously abuse Sync Contributions button

### ISSUE THREAD

**Issue by vivganes** [joshsoftware/code-curiosity#182]
Once I press the Sync Contributions button, while the http request is in progress, the button can be clicked again.  

If I am on low bandwidth like mobile internet, it takes some time for confirmation message to appear. By that time, user would click the button again multiple times sending the Same request. It is also possible to maliciously keep clicking the button thereby increasing the load on server.

The ideal behaviour would be that the button is disabled until the time http response from server is received.

**Comment by prasadsurase** [comment]
@vivganes We maintain the timestamp of the last data sync. this is considered when user tries to resync the data. The time gap that we consider is 1 hour.

**Comment by vivganes** [comment]
That's awesome! I will close the ticket since there is no possibility of malicious use.  

However, will it be possible to start showing some message immediately after the user presses the button so that he does not go for a second press? In case of mobile internet, it takes a long time for the message to appear, which leads people in confusion whether the button was pressed or not.
