### ISSUE TITLE
Missing link for User's 'Repositories' but page is loaded when accessed through url.

### ISSUE THREAD

**Issue by prasadsurase** [joshsoftware/code-curiosity#184]
Any logged in user can access his/her repositories by altering the url but the link for the same is missing from the UI.

**Comment by amitk** [comment]
@gautamrege We sync/retrieve the repositories of the user and persist them if they meet the criteria(stars should be greater than N). Sometimes, the repository isn't persisted and hence we cant retrieve the commits and activities. This results in the user unable to view their commits and activities for the concerned repo. If we display the repositories of the user as 'My Repositories', he/we can detect any missing repository. We already have the page for the same but the link is absent. Should we remove the page or add the link?
