### ISSUE TITLE
Commits status "In review" from a very long time

### ISSUE THREAD

**Issue by Princu7** [joshsoftware/code-curiosity#187]
@gautamrege First of all, Happy Diwali Sir. 
This issue was resolved in the past but it seems to have crept up again. It's been 4 days since I made some commits and they are still in the "In review" status. October is almost over and these commits will probably get lost once the new month begins. 
Here is the screenshot
![screenshot from 2016-10-30 11-32-06](https://cloud.githubusercontent.com/assets/8847265/19834804/224854c0-9e95-11e6-82b1-22535945b5c5.png)
Please look at this when you have some spare time. Thank you so much for your time and for building this amazing platform.!!

**Comment by anshuman73** [comment]
I'll have to agree there is a visible amount of lag in reviewing the activities as compared to before. Is it a server issue or anything else we can help solve ?

**Comment by Princu7** [comment]
@gautamrege  Thanks. This problem seem to have been fixed. Maybe it was the server issue which was taking some time to evaluate the commits. But it seems the more I contribute in terms of lines of code, the lesser points I get for them. In previous month, I had made 9 commits having a total of 50-60 lines of code. In this month of October, I made 11 commits having about 550 lines of code. But the points I received for them is even low than the previous month. Please review the evaluation algorithm. Anyways, since the issue has been fixed, please close it.
