### ISSUE TITLE
Are wiki edits scored? 

### ISSUE THREAD

**Issue by redfast00** [joshsoftware/code-curiosity#206]

**Comment by sethu** [comment]
Scoring is done only for the github repositories. As of now, code curiosity doesn't score editing wiki pages directly on wikipedia.

**Comment by redfast00** [comment]
@sethu: I don't mean wiki pages on Wikipedia, but on GitHub like https://github.com/pivpn/pivpn/wiki

**Comment by sethu** [comment]
In that case, it will score.

**Comment by redfast00** [comment]
Where can I find wiki edits? It isn't under activities or commits and other comments after the edit are scored.

**Comment by sethu** [comment]
Did you run a "sync"? I could see scores for pivpn

**Comment by redfast00** [comment]
@sethu: I did run a sync, and more recent comments are showing up and are already scored. I created the FAQ wiki page of pivpn yesterday, and this isn't in my activities feed.

**Comment by redfast00** [comment]
@sethu: can you please reopen this issue?

**Comment by sethu** [comment]
@redfast00, I miss understood github Wiki changes isn't consider for scoring. Currently, it consider only the commits, issues creation and issue comments.
