### ISSUE TITLE
Issue in Java Scoring - Got zero score for a bug fix contribution

### ISSUE THREAD

**Issue by vivganes** [joshsoftware/code-curiosity#207]
The algorithm behind scoring of Java commits seems to have a bug(or may be not - it could be a conscious decision that you guys made).  I got zero score for what is a valuable code change (Not change of docs or comments) that would fix a bug in the rcarz/jira-client repository.

This is the commit that  I am talking about: https://github.com/vivganes/jira-client/commit/7ea6f3b7d50f0bc1fdb318425bb8c2b731de5bf4

The diff of this commit is as follows

```
-            if(!(value instanceof java.lang.Integer) && !(value instanceof java.lang.Double) && !(value 
+            if (value == null) //Non mandatory number fields can be set to null
+                return JSONNull.getInstance(); 
+            else if(!(value instanceof java.lang.Integer) && !(value instanceof java.lang.Double) && !(value 
```

This fixes a bug that would prevent a functionally possible update in JIRA because of coding defect in the client library.

Sounds like a case for improvement of scoring algorithm.  Just thought of raising an issue to investigate.

**Comment by sethu** [comment]
@vivganes, thank you for raising the issue. As you know the system is evolving and we will investigate and fix the algorithm.

**Comment by vivganes** [comment]
Thank you very much, @sethu 

I understand that this system is evolving and you guys are doing a great work!  I raised this issue in order to provide inputs to the evolving system only. Thanks for taking it up for investigation.

One question though: Does this mean that there is a possibility that I will get a manually allocated score sometime soon for my commit?

**Comment by prasadsurase** [comment]
@vivganes As of now, a scored commit isn't taken up for rescoring.
