### ISSUE TITLE
Goals page suggests to redeem 550 points but single redeem is capped at 500

### ISSUE THREAD

**Issue by tcNickolas** [joshsoftware/code-curiosity#219]
It is unclear how to redeem 550 points if you can only redeem 500 in a single action. Maybe user is supposed to redeem points as gift cards instead of an item and combine several months' worth of them to get the item? It would be nice to clarify this in descriptions

**Comment by prasadsurase** [comment]
@tcNickolas We do display the Redeem Points rules and limitations on the Redeem Points page.

**Comment by tcNickolas** [comment]
@prasadsurase What I mean is: https://codecuriosity.org/goals says "Redeem 550 points (~55$)..." which is impossible to do according to the Redeem Points page.

**Comment by BandanaPandey** [comment]
@tcNickolas you can redeem 550 points in any round, but the limitation is on **Royalty points**  that is, for any round atmost 500 Royalty points can be redeemed, not more than that.
As you can see this rule on on the Redeem Points page.
![codecuriosity2](https://cloud.githubusercontent.com/assets/16642417/21090588/b910f0cc-c066-11e6-9ad6-2c94476866ff.png)

**Comment by sethu** [comment]
@tcNickolas, I got your point. The drop down restriction is for github gift, because github only gives only 3 options. However, you can use amazon gift for any amount.
<img width="992" alt="screen shot 2016-12-12 at 13 10 56" src="https://cloud.githubusercontent.com/assets/109757/21091447/38ea8f2e-c06c-11e6-9b2d-cdede3eab113.png">

**Comment by tcNickolas** [comment]
@BandanaPandey I see, I didn't realize that royalty points are not the same thing as regular points (since I don't have any royalty points in my profile). Looking forward to redeeming 550 regular points for a hoodie then :-)

@sethu Should I keep this issue open until the goal page is updated?

**Comment by Anshuman-Verma** [comment]
Are royalty points the ones we are rewarded as goal achieving bonus ? or are they something different ?

**Comment by tcNickolas** [comment]
@Anshuman-Verma My understanding is that royalty points are points awarded to owners of repositories which have 50+ stars for some sort of activity on these repositories. Haven't had a chance to verify this understanding on my repos yet :-)

**Comment by Anshuman-Verma** [comment]
Hey thanks ! @tcNickolas

**Comment by wyhaines** [comment]
Closing. Issues with pointing and redemption will all be looked at as other adjustments are made in coming weeks.
