### ISSUE TITLE
Registration 

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#22]
Anyone with a github account can register on Code Curiosity. 

* When you successfully register, you will automatically be part of the current on-going round.
* You can manage your team.
* You can manage your repository. 
* You can see dashboards for different rounds.

**Comment by Sameer-Tilak** [comment]
Can member if part of more than one team in same round? If no that will be ideal
If yes, then will hos individual contribution be considered as sum of all points from all teams?
