### ISSUE TITLE
Activities page crash

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#224]
https://codecuriosity.org/activities page crashed. Looks like It happens to my login ID only. On debugging, all my repositories got deleted but respective commits didn't get deleted.

**Comment by amitk** [comment]
@sivagollapalli Please let us know if you are facing this problem even now, if you are not facing such issue please close this issue

**Comment by sivagollapalli** [comment]
@amitk Currently I am not facing this issue Closing the issue.
