### ISSUE TITLE
Contact details for redeem code

### ISSUE THREAD

**Issue by jsroyal** [joshsoftware/code-curiosity#238]
@sethu, @BandanaPandey @prasadsurase
-100	Redeem points DEBIT AMAZON	04/Jan/2017 13:11:06

Till now I did not get any update from your side.
So where is the contact point in the web page?\
Usually, we redeem points within 1 or 2 days. All redemption requests are screened by our fraud detection team. We have come across cases of fraud (unfortunately) where users were trying to manipulate the system to make money in unfair ways. We have ejected these users from the system. This is indeed a sign that the initiative has been successful :) If your redemption request is not processed within 4 days, please contact us and we shall discuss the reasons behind the delay.

**Comment by sethu** [comment]
We have evaluated your commits and activities but didn't convince as valid open source contribution. Below are the commit lists, if you can justify what you have done and why there isn't any pull request send.

https://github.com/jsroyal/google-interview-university/commits/master?after=Y3Vyc29yOvMaYcBrnBSWqUpVCzHNpe7SeZyHKzM0

**Comment by jsroyal** [comment]
Thanks @sethu  Basically it is a repo for yourself learning and according to your motivation, I used edited my readme file for according to my preparation.This was my winter vacation free time so I did it.So there is not any sense send a pull request from origin repo because it is indidule preparation for Google university how much you can follow from your origin source . 

and also my see my other contribute I'm helping to improve readme file which most effective any open source user.
If you don't reward me then so be it but I actually start to kick start from here inspired. and keep going and going with it.
I don't think any wrong I did basically I just hope one Huddy show my colleagues to inspire them to come with me and join open source.They always just download the project, not event complete read readme file.I inspire to from the concept of it and that was my motive for join with code curiosity and it is the great concept to join newcomers in open source.

**Comment by sethu** [comment]
It is for personal use then it doesn't fall under open source. Don't worry about the reward point, keep contributing the open source. Once the panel finds it is genuine open source contribution, we will redeem the points.

**Comment by jsroyal** [comment]
@sethu  That okay. I don't want but my issue was to add a contact point in code-curiosity website.
So if somebody has  query then need to reach out point.

**Comment by jsroyal** [comment]
@sethu Still does not add this point entry so I think without any suggestion closing issue does not make sense.
So my point has any argue with not have a contact point in CodeCuriosity.

**Comment by sethu** [comment]
I was waiting for your pull request ;)

**Comment by jsroyal** [comment]
@sethu  Sure! thanks :)
