### ISSUE TITLE
Previous contributions not counted 

### ISSUE THREAD

**Issue by shubheksha** [joshsoftware/code-curiosity#239]
The contributions show up in my profile after syncing. However, I do not get points for any of them. They're still "in review" even though the PRs have been merged. https://github.com/webpack/webpack/pulls?q=is%3Apr+author%3Ashubheksha+is%3Aclosed

EDIT: I could only sync contributions for Jan. I see only November and December in the dropdown and when I try to sync contributions for them, it doesn't work. I don't see previous months in the drop down at all.

**Comment by prasadsurase** [comment]
When an user joins CC, the contributions for only the current month are retrieved. We do not retrieve any contributions from the previous months.

**Comment by shubheksha** [comment]
@prasadsurase, alright. What about everything being "in review" despite being merged?

**Comment by prasadsurase** [comment]
@shubheksha Currently, retrieved commits have no association/dependency on merged commits. The number of blocks denotes the points. If the block is grey, it means the score is 0. Only unscored activities and comments are in 'In-Review'. As for your total points being displayed as 0, they will be updated once the Round ends. You can view your current points(points for the current month) on the graph.
