### ISSUE TITLE
Comment not updated

### ISSUE THREAD

**Issue by redfast00** [joshsoftware/code-curiosity#240]
I commented on an issue, but mispressed the 'Submit' button, so I had to edit my comment. When I checked this on codecuriosity, it still had the old text and it probably also awarded points for that text. Is it possible to re-sync? https://github.com/pivpn/pivpn/issues/183#issuecomment-272144550

**Comment by prasadsurase** [comment]
@redfast00 Once data from Github has been retrieved, it isn't synced with Github again.

**Comment by redfast00** [comment]
It would be cool if there was a button to resync. Probably won't matter anymore though, since it's then end of the month.

**Comment by amitk** [comment]
@redfast00 Now we don't have this feature so, please close this issue.
