### ISSUE TITLE
Requesting to display notice about additional charges while redeeming rewards

### ISSUE THREAD

**Issue by vivganes** [joshsoftware/code-curiosity#241]
I redeemed rewards and got a Github token to buy a t-shirt.

I was charged a customs duty by Indian customs authority to the tune of 844 rupees.  Also, I was charged a shipment fee of around 350 approx too.

```
Shipping Charge - 350
Customs Duty - 844
============================
Total - 1194
```

This is basically around 1200 rupees for a t-shirt which clearly does not go well with the going rates in India. It looked like I had to pay just because I got this reward or else I wouldn't have spent this money at all. 

It would have been easy if you guys display a notice so that people use the system in alternate way (domestic instead of international shippers).

Thanks for your noble intention but just that it would be even more awesome if the returns are proportional too  :)

Kudos to your team :)

**Comment by sethu** [comment]
This how the international shipment works. However, there is an option to choose between Amazon or github. For Amazon, we provide an option to choose between Amazon.in, Amazon.uk or Amazon.com.

**Comment by shubheksha** [comment]
@vivganes, what shipping method did you use? Customs duty for a $25 shirt seems absurd. I've gotten swag for more than that value shipped to me without any hassles with customs.
