### ISSUE TITLE
Points don't get updated on the dashboard and the profile page

### ISSUE THREAD

**Issue by shubheksha** [joshsoftware/code-curiosity#245]
Since the beginning points don't get updated in these places.

<img width="1206" alt="screen shot 2017-01-24 at 4 50 33 pm" src="https://cloud.githubusercontent.com/assets/7693422/22245326/6a85e118-e255-11e6-9f5c-e615e12996f2.png">
<img width="1209" alt="screen shot 2017-01-24 at 4 51 02 pm" src="https://cloud.githubusercontent.com/assets/7693422/22245329/6b9a40da-e255-11e6-8d3a-28e72bf176fe.png">

**Comment by prasadsurase** [comment]
@shubheksha Your CC account has been created on 9th Jan 2017. The points(212) are the points for the **scored** commits and activities till date(and of the current round/month). If you visit your profile page, you would notice that your current points are 0. The total points for a round are added to the user's account after the rounds end. Usually, commits and activities are scored the following day. Currently, all your commits and activities till 23rd January are scored.

**Comment by shubheksha** [comment]
Alright, thanks for the clarification! :)
