### ISSUE TITLE
Commits not being tracked after repo was transferred

### ISSUE THREAD

**Issue by Roshanjossey** [joshsoftware/code-curiosity#247]
My commits to https://github.com/Roshanjossey/first-contributions were tracked correctly by codecuriosity.

On 29/Jan/2017, I transferred the repository to https://github.com/multunus/first-contributions.

After that, my commits are not being tracked for the same repo. Activities are getting tracked as expected

**Comment by Roshanjossey** [comment]
Now I see none of my commits are getting tracked. Today I made a commit in https://github.com/shanselman/firsttimersonly

That was also not tracked. Nothing after 29/Jan/2017 is getting tracked

**Comment by prasadsurase** [comment]
@Roshanjossey As of now, the [Github API](https://github.com/piotrmurach/github) gem being used to retrieved the commits of a repository doesn't support redirection and hence we can't handle this case. A PR regarding the same has already been sent but hasn't been merged and released for use.

**Comment by Roshanjossey** [comment]
@prasadsurase: Also the commit for the PR https://github.com/shanselman/firsttimersonly/pull/26 was also not tracked. Could you comment on that?

Is it like any request to the repo  https://github.com/multunus/first-contributions. is getting redirected through  https://github.com/Roshanjossey/first-contributions. Even if someone goes to the original link? If not shouldn't codecuriosity track that repo separately anyway?

**Comment by prasadsurase** [comment]
@Roshanjossey HTTP requests are redirected by Github to the new source. We don't consume the Github API directly but access it through a gem(library). Unfortunately, the gem(library) doesn't support redirection. Also, that's the only gem which supports Github APIs.

**Comment by wyhaines** [comment]
https://github.com/piotrmurach/github/commits/58f1f8395f238ade7560a371e1981c3934b6bea4/lib/github_api/response/follow_redirects.rb

It appears that redirect following was added to the gem, so I am going to close this issue on the assumption that redirects now, almost 4 years later, work.
