### ISSUE TITLE
Cannot change current month goal.

### ISSUE THREAD

**Issue by zeus999** [joshsoftware/code-curiosity#254]
As I signup recently and I set my goal to hiker, but is there is no way to change my current month goal.
Should I raise a PR for the same, if not then why this feature is not required ?

**Comment by SagareGanesh** [comment]
@zeus999 This issue ia already discussed, please refer [this](https://github.com/joshsoftware/code-curiosity/issues/130).

**Comment by amitk** [comment]
@zeus999 As this issue had been already taken care of please close this issue.
