### ISSUE TITLE
Approved PRs not adding to Activities

### ISSUE THREAD

**Issue by vishnuchilamakuru** [joshsoftware/code-curiosity#264]
I already raised PR and it got approved. But its not getting added in my Activities page.

PR raised :  #https://github.com/sferik/twitter/pull/833

<img width="1627" alt="code_curiosity" src="https://cloud.githubusercontent.com/assets/1097838/23360778/4ed8b412-fd13-11e6-82fc-e3ad991d2ac6.png">

**Comment by prasadsurase** [comment]
@vishnuchilamakuru We do not persist PR related activities.

**Comment by amitk** [comment]
@vishnuchilamakuru we only consider issues and comments as activities not PR related activities so, please close this issue.
