### ISSUE TITLE
Contributions not getting synced and in review for a long time.

### ISSUE THREAD

**Issue by ferbncode** [joshsoftware/code-curiosity#274]
My contributions for the month of April have not been reviewed yet. It would be great if someone could help me with this. Thanks!!

**Comment by prasadsurase** [comment]
@ferbncode You have only 1 commit and no activities for April. The commit for April has been scored.

**Comment by ferbncode** [comment]
@prasadsurase. Thanks!!. Here is a screenshot of my contributions not being scored. Also, I have more than 1 commit in April.
![12](https://cloud.githubusercontent.com/assets/12391372/25278367/4641970c-26c0-11e7-8774-9f6208b1a573.png)

**Comment by ferbncode** [comment]
This issue seems to be resolved. Thanks for all the help!!
