### ISSUE TITLE
Subscription to CodeCuriosity as a sponsor

### ISSUE THREAD

**Issue by tejaswini-gambhire** [joshsoftware/code-curiosity#276]
- There will be a floating button "sponsor" at the right side of each page throughout the website whether user is logged in or not and if he is not a sponsor already.

- There are four cases of sign in as sponsor:
  1. Fresh log in as sponsor: A new user will sign up as a sponsor to the system.
  2. Second time log in as sponsor: A user who is already sponsor will log in to the system.
  3. Existing user clicks on sponsor after log in to CodeCuriosity
  4. Existing user clicks on sponsor before log in to CodeCuriosity.

- Except second case after clicking on sponsor button user will see a popup with two tabs(first time sign in as sponsor)
  1.  Sponsor as individual
  2.  Sponsor as Company
- The popup will have following details:
  1.  Profile photo for individual and logo for company.
  2.  Payment schedule:
      - for individual  10, 15 or 20 dollars.
      - for company  150, 200 or 300 dollars.
     ( Indiviadual or company will choose on of these payment schedule)
  3. Checkbox for permission to show profile photo of the sponsor.

- After sign in as sponsor he will see the dashboard where he can see the payments.
- For an existing user who is also a sponsor,  tabs of a normal user( contributions, groups, points etc.)
  will also be displayed along with sponsor tab.

**Comment by tejaswini-gambhire** [comment]
- Sponsorer will do recurring payments for that he will subscribe a plan at the time of sign up as 
  sponsor. ( Plans are described in payment schedule )
- The subscription can be renewed after one year.
- He can sponsor for a particular repository or for all repositories.
- A non existing user who will subscribe to code-curiosity as sponsor will be asked to set the goal if he 
  wish.

**Comment by wyhaines** [comment]
This needs more digging to fully understand the scope here. Keeping this open.

**Comment by wyhaines** [comment]
Closing.  This was left open, but the branch was merged in Jul 2017, so......???
