### ISSUE TITLE
codecuriosity.org seems to be down

### ISSUE THREAD

**Issue by paramsingh** [joshsoftware/code-curiosity#279]
Hi, you guys probably already know this but, just in case you don't, the site seems to be down right now.

This is what I get when I try to open the site. 

![screenshot_2017-05-22_21-00-34](https://cloud.githubusercontent.com/assets/1837631/26316426/de1874cc-3f31-11e7-8bda-6e7b4c0a5635.png)

**Comment by Anshuman-Verma** [comment]
It's back ! Must have been some server issue.

**Comment by Anshuman-Verma** [comment]
Must've been some server issue, it's back anyways so this issue can be close now.
