### ISSUE TITLE
Commits under review for last month not added

### ISSUE THREAD

**Issue by Anshuman-Verma** [joshsoftware/code-curiosity#281]
I had some 200 commits under review till 31-5-17 and now the contributions count is reset and no points are rewarded for those un-reviewed commits, Kindly provide a resolution ASAP. @sethu @gautamrege

**Comment by Anshuman-Verma** [comment]
[Update] 
Commits visible now and are under review

**Comment by sethu** [comment]
As I communicated in the email, awesome-no-login-web-apps won't be consider for points.
