### ISSUE TITLE
Commits perpetually in review

### ISSUE THREAD

**Issue by paramsingh** [joshsoftware/code-curiosity#282]
Hello, this May, my commits had been in review for a long time and in the end, they did not get evaluated. I have the same problem now, as commits from a few days ago haven't been evaluated yet while more recent activities have been evaluated. Could someone please take a look and see what is happening? The points lost don't matter much to me, but if none of my commits get evaluated at all, CodeCuriosity becomes hard to use for me. :frowning_face: 

Here are screenshots showing my commits in review: 

Last month

![screenshot_2017-06-01_01-45-40](https://cloud.githubusercontent.com/assets/1837631/26731691/75ee4ea4-47d2-11e7-8317-a78c68ffb960.png)
![screenshot_2017-06-01_01-45-48](https://cloud.githubusercontent.com/assets/1837631/26731690/75e4c456-47d2-11e7-8832-15487be9f2a7.png)
![screenshot_2017-06-01_01-45-53](https://cloud.githubusercontent.com/assets/1837631/26731692/75f2c556-47d2-11e7-8bcb-8649cfc3344c.png)

This month: 
![screenshot_2017-06-01_15-00-40](https://cloud.githubusercontent.com/assets/1837631/26731705/7e695f06-47d2-11e7-826e-a6f860c03e7b.png)

**Comment by code-note** [comment]
Many are facing the same problem, only some recent activities get evaluated while the old ones are in review since long. I hope they fix this asap.

**Comment by gautamrege** [comment]
We're on it. Hang in there. CodeCuriosity IS getting popular and this is causing some storage and computation crunch.

**Comment by paramsingh** [comment]
I think this might be more of a bug than resource scarcity, given the fact that literally none of my commits have been evaluated since the 21st of May. I hope you take a closer look. Thanks!

**Comment by tcNickolas** [comment]
This looks like a reoccurrence of https://github.com/joshsoftware/code-curiosity/issues/235, so whether it's caused by a bug or by resource bottlenecks, it's been around for at least 5 months.

**Comment by jsroyal** [comment]
Some time I have same issue 
![image](https://user-images.githubusercontent.com/10773353/27993350-0e12ad40-64c7-11e7-9c38-55b394b068ad.png)

But I think the reason  true.
> We're on it. Hang in there. CodeCuriosity IS getting popular and this is causing some storage and computation crunch.

**Comment by amitk** [comment]
@tcNickolas @code-note @paramsingh @jsroyal All your commits and activities for the current round have been scored. @paramsingh please close the issue if you agree.

**Comment by paramsingh** [comment]
Looks like it, thanks! :)
