### ISSUE TITLE
Activities reviewed and scored but not added to this month points

### ISSUE THREAD

**Issue by tcNickolas** [joshsoftware/code-curiosity#284]
My activities since the beginning of June are shown in Contributions with some points assigned to them, but the number of points for June on the dashboard is 0 (the number of activities on the dashboard is correct).

![image](https://user-images.githubusercontent.com/10113024/26987807-c14c506a-4d01-11e7-8967-e2df92df1dd4.png)

![image](https://user-images.githubusercontent.com/10113024/26987776-af5fccd8-4d01-11e7-9b71-c6a19a2f03a1.png)

**Comment by Anshuman-Verma** [comment]
Exactly the same problem, infact I came here to open an issue and saw yours.
Others are having their activities scored (as followed in trends)
I have even mailed them twice but they haven't gotten back to me yet. :disappointed:

**Comment by sethu** [comment]
Total points of the month will be added at end of round, i.e., end of the month

**Comment by Anshuman-Verma** [comment]
Thanks for notifyting @sethu but the problem is that the monthly points aren't getting updated despite the activities being scored.

**Comment by tcNickolas** [comment]
@sethu At the end of the month the current points (circled on the second screenshot) are added to overall points (blue rectangle), but during the month the current points are supposed to be growing.

That being said, the problem is resolved for me, current points show correct value. Thank you.
