### ISSUE TITLE
Https certificate errors

### ISSUE THREAD

**Issue by redfast00** [joshsoftware/code-curiosity#286]
I sometimes get HTTPS certificate warnings in Chrome. `NET::ERR_CERT_AUTH_INVALID`. https://www.ssllabs.com/ssltest/analyze.html?d=codecuriosity.org&latest here's an analysis of your HTTPS setup. I recommend you switch to Let's Encrypt free certs.

**Comment by sethu** [comment]
Updated the cerificate

**Comment by redfast00** [comment]
@sethu: have you seen the reports page? The certificate chain is incomplete and apparently the server is vulnerable to all sorts of attacks. Can you please reopen this issue?
