### ISSUE TITLE
How to see old contribution?

### ISSUE THREAD

**Issue by SagareGanesh** [joshsoftware/code-curiosity#290]
Is there any way to see all old contribution i.e more than last 3 months?

**Comment by amitk** [comment]
@SagareGanesh  we don't have such feature right now. Current feature only shows contributions pertaining to an user current subscription. If you believe that our application should have a feature like that please send us pull request.

**Comment by wyhaines** [comment]
This might be a good idea to revisit later.  Closing for now.
