### ISSUE TITLE
Didn't receive coupon code for points redeemed at starting of May yet

### ISSUE THREAD

**Issue by Princu7** [joshsoftware/code-curiosity#291]
I am sorry for opening an issue of this sorts. I know you guys work very hard to keep this platform going and I can't be more thankful for it. It gave me the much-needed push to contribute to the world of open source.

But this issue highlighted in the heading has been disappointing and demotivating. I redeemed 400 points at the starting of 1 May. And I haven't received any coupon code yet for it. I tried to comment on earlier issues opened in the same vein, send a mail to the support staff at `info@codecuriosity.org` but received nothing. Please see to this issue. I know it takes time but even them it's been quite a while. I hope you understand. And thanks again for building this amazing platform.

**Comment by sethu** [comment]
There are around $600 worth of redemption pending we are clearing it one by one. As you know, we are paying it from our own packet. So, be patient and keep up the good work. Also, see if you can help in finding a sponsors.

**Comment by Princu7** [comment]
Thanks for following up :)
