### ISSUE TITLE
Change email-id

### ISSUE THREAD

**Issue by Roshanjossey** [joshsoftware/code-curiosity#309]
This is more of a question.
The primary e-mail I had set on GitHub when signing up for codecuriosity is now disabled.

I used to get mails from codecuriosity to that mailId. Now I've changed my primary mail in GitHub.

Will this change be reflected in codecuriosity? Should I do anything to change this?

**Comment by prasadsurase** [comment]
@Roshanjossey Code Curiosity updates your details every-time you login. These details are retrieved from GitHub. You need not make any changes on Code Curiosity.
