### ISSUE TITLE
Scoring commits and activities as soon as they are retrieved from Gtihub.

### ISSUE THREAD

**Issue by prasadsurase** [joshsoftware/code-curiosity#311]
Currently, we [schedule](https://github.com/joshsoftware/code-curiosity/blob/master/config/schedule.rb#L28) the scoring of commits and activities daily. Also, the scoring rake tasks creates a [single](https://github.com/joshsoftware/code-curiosity/blob/master/lib/tasks/auto_score.rake#L7) sidekiq job for scoring all the commits for a repository. What if we create individual sidekiq jobs for every commit as soon as it is retrieved? This way, even if a job fails to score a commit because of any issue(eg. many a times, the branch featuring the commit is deleted as soon as the PR is merged), the rest of the commits will be scored. Thoughts?

**Comment by amitk** [comment]
@prasadsurase Yes, It's a good idea. It will also decrease the time application takes to score commits and activities and will increase our application efficiency.

**Comment by wyhaines** [comment]
It appears that a PR for this was merged, so I am closing this.
