### ISSUE TITLE
My contribution history before joining codecuriosity.org doesn't show up

### ISSUE THREAD

**Issue by leovarmak** [joshsoftware/code-curiosity#313]
Hey,
The contributions I made prior to joining codecuriosity haven't been showing. I tried to Sync many times but nothing happens. I did contribute to many sites having more than 100 stars.
My username is `leovarmak`

Regards,
Karthik

**Comment by amitk** [comment]
@leovarmak Hi,
Code Curiosity doesn't show commits and activities of past. It only shows your commits and activities that you have performed after joining code curiosity.

**Comment by gautamrege** [comment]
@leovarmak we cannot get all your past contributions like @amit has mentioned. However, we reward your past contributions by giving you "Royalty points" based on contributions, your followers, your contributions consistency, repos ownership and it's stats and various other criteria.

**Comment by leovarmak** [comment]
Oh. Thank you
