### ISSUE TITLE
Judging

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#32]
In community edition, there are no teams - it's all individuals. Scoring is from a range of 0-5.
Each commit and activity has to be judged by any 3 judges before we lock the score.

Distribution of work between judges
===

* based on expertise in languages.
* time availability.

Based on these factors, the system should send commits or comments for judging. This is the minimum effort expected based on their settings of language and time. The remuneration for judges will be decided on these factors. The judges can also explore other commits and activities and their incentives would be based on how active they are.

*note* A judge can be a contributor, so the system should never send judges own activities to himself or herself. 

Process (keeping the judges on their toes)
===

Judges will not be able to see others scores until they have judged the commit or activity. (just like a poll). After that, they can not only see what other have scored but can also change their score if they fell they should. They must then confirm their score.

This will ensure that judges *have* to score based on their judgement and not others judgment. Since the discrepancy and score change are metrics that judge the judges, this will introduce a good checks & balances system for judging. 

Judging the judges
===

Criteria needs to be decided but broadly these are the factors:
+ Number of discrepancies for your score. If there is a discrepancy in score, both judges discrepancy count is incremented.
+ How often did the judge change their scores.
+ Number of scores given.
+ How often have they completed their minimum assigned work
+ How much of extra scoring did they do. i.e. over commitment to the system.

Recommendation Scores
===
 To start with, these are guidelines given to the judges! 

0 - ignore because its a duplicate or irrelevant comment.
1 - documentation changes, typos, etc. 
2 - minor code change, bugs (less than 5 lines changed)
3 - large code change, bugs, build passed (more than 5 lines and less than 50 lines)
4 - features added, critical bug (more than 50 lines)

*note:* system will never recommends 5. That is at judges discretion.

As we start seeing how the judging is done, system will start to recommend a score to reduce the judges effort.

Score discrepancy 
===

If there is a difference of 2 between any scores, then a comment is mandatory and a notification goes to the other judges who have score difference of more than 2. The other judge must then complete some action: either leave a comment "retain my score"  or change the score to within a factor of 1 from other judges.

Baseline: All scores must have a difference of 1 unless the judge(s) has explicitly retained their score.

**Comment by anujaware** [comment]
Scoring can not be done only on number of lines changed. There are other factors need to be considered like sometimes for small change you need to learned a lot if its a large repository and when it affects in so many places. Or sometimes large number of lines may not be that valuable. Also we may need more numbers (score) for judging ;)

**Comment by gautamrege** [comment]
@anujaware This is not automated scoring but a guideline. The judging is for the scoring not the learning. So initially you will take a lot more effort and have very little to show for it but if you are consistent with your work on that repos - the scores will get bigger as you will make larger fixes! 

5 is enough for a score range - we were contemplating 4 (like a GPA) but have kept it to 5. We need to minimise discrepancies. Of course, in due course if we deem fit, we shall increase the range.

**Comment by anujaware** [comment]
:+1:

**Comment by anilmaurya** [comment]
2 Minor code change will give me 2 + 2 = 4 points.
1 feature will give me 4 points.

Its very easy to make 2 minor change Vs 1 feature.
Indirectly code curiosity is encouraging minor changes instead of feature building.

I support 0-9 scoring range .

**Comment by gautamrege** [comment]
@anilmaurya We are scoring each commit and it's highly unlikely that you have a feature with 1 commit. (if that is the case, I'm not sure that would be considered a feature. If you had 1 commit with 4,000 lines of code, changes are it's going to be rejected anyway).

So, for a feature, you may have 10-15 commits with various ranges of scores.

**Comment by pramodshinde** [comment]
:+1: @anilmaurya - Its not always true that feature have 10-15 commits, many times authors asks to quash the commits for feature as well.

**Comment by gautamrege** [comment]
well said @pramodshinde We need to think about how to score squashed commits.

The thing is that we know that the squashed commit has multiple commits in it - but how will we judge that? Do we keep a "multiplier" element in scores if we detect squashed commit?  Of course, if the user deletes the squashed commit details from the comment, there is nothing we can do about it. 

@jiren, thoughts ?
