### ISSUE TITLE
Few commit scores not added to final points

### ISSUE THREAD

**Issue by Anishka0107** [joshsoftware/code-curiosity#329]
A few of my commits for the month of July were in review for a long time, and were finally scored in August. Now they have not been added to my final points of July. I wonder whether they'll be added to my final points of August. Or will I lose them? :(

**Comment by amitk** [comment]
@Anishka0107 If your commits are of July the points that they scored will be add to your final points of July not to points of august.

**Comment by Anishka0107** [comment]
Yeah, but they weren't added to the points of July. Seems like July scores are now final, and they don't include scores of a few commits I did in July, which got scored in August.

**Comment by wyhaines** [comment]
This is related to other previously closed issues. If this appears to be a problem after we are doing updating everything, a new ticket will be opened to address it.
