### ISSUE TITLE
Gamification Terminology.

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#34]
We need some good names for the following:

Terminology for scores.
===== 

We earn them and use them for each round as a subscription fee. Lets get a new terminology for this i.e. rather than saying points, coins, dollars etc. lets say we earn "-----" something easy to type and pronounce and it should be catchy, so you are proud of it. 

Badges
=====
 What type of badges can we give for what criteria. Example, in Fitbit, you get a "Serengeti badge" if you run 804 km till date. Some criteria:

* A badge for consistently getting more than 20 points in 3 consecutive rounds? What would be a good name.
* A badge for a big leap of more than 40 points in consecutive rounds.
* A badge for consistently participating in 5 consecutive rounds.
* A badge for consistently participating and not scoring more than 2 points in 2 rounds! (some badge like medication to encourage more participation). 

Other criteria which matter to you? Suggestions welcome.

**Comment by rishijain** [comment]
how about "gitcoins" ?. They are bitcoins but for github. :)

**Comment by Sameer-Tilak** [comment]
lets call it as 'pebbles'.

Regards,
~Sameer

<http://in.linkedin.com/in/gautamrege>

**Comment by pramodshinde** [comment]
How about mapping analogies to insects/animal and their behavior 

* A badge for consistently getting more than 20 points in 3 consecutive rounds? => :horse: 'Horse' or :lion 'Lion' or :wolf:  'Wolf' (Wolf of open source)
* A badge for a big leap of more than 40 points in consecutive rounds. => 'Grasshopper' - A rapid plant-eaters - here rapid issue resolver 
* A badge for consistently participating in 5 consecutive rounds. => :ant: 'Ant' - Ants form colonies - here participant 
* A badge for consistently participating and not scoring more than 2 points in 2 rounds! (some badge like medication to encourage more participation). =>  :snail: 'Snail' (slow and steady)

We can evolve more innovative badge around this.

**Comment by Lakshmi-Sharma** [comment]
Pramod's idea of mapping insects/animals sounds interesting to me.

If we use it, we could use something like 'dyne' or any other suitable
energy metric for scores.
So the players get animal badges and energy as score.

Regards,
Lakshmi

**Comment by anilmaurya** [comment]
+1 for pramod's Idea.

**Comment by anujaware** [comment]
:+1: I like this idea too.

**Comment by yogeshjain999** [comment]
+1 for @pramodshinde idea.

**Comment by jiren** [comment]
Also we can use names of superheroes and modify names to avoid copywrite or trademark issue.
i.e
http://www.comicvine.com/profile/kagetaicho/lists/100-most-powerful-marvel-characters/10144/
http://www.comicvine.com/profile/theoptimist/lists/top-100-marvel-characters/32199/

**Comment by gautamrege** [comment]
People - great ideas.  What more rules can we give badges to apart from the ones we have mentioned.

We need at least 10 badges. We also need to think about ideas around the currency exchange - contributors collect "points" and I don't like that terminology -- what could it be? Jewels, exotic elements, flowers, etc. - something **exciting** that can be exchanged for actual money!

**Comment by Lakshmi-Sharma** [comment]
We could use '*Dyne*'. It a unit of force or energy. It will match with the
theme of Animal Kingdom.

Regards,
Lakshmi
