### ISSUE TITLE
My commits are scored zero

### ISSUE THREAD

**Issue by mishraanmol** [joshsoftware/code-curiosity#345]
My few commits are being scored zero, though the repo has 25+ stars and I have got my PR merged.
Can anyone tell me how this is happening?
How exactly are scores calculated?
@anuj-verma @gautamrege 
Please help me out

**Comment by amitk** [comment]
@mishraanmol You don't have any commits synced with Code Curiosity. This reason is that none of your repositories was rated(had 25+ stars) when it was synced with Code Curiosity.

**Comment by mishraanmol** [comment]
@amitk How can I avoid anything like that in future?
Does the repository holder should also be on Codecuriosity?

**Comment by gautamrege** [comment]
Just click on “Contributions” menu item and then “Sync Contributions”.. this should fix it.

**Comment by mishraanmol** [comment]
It did not work either!

Any other alternative or help.
I tried that for about a day ago already, my recent commits are being reflected in my Github profile but not in codecuriosity. :(

**Comment by anilmaurya** [comment]
### Other alternative is to really contribute to open source.
![screen shot 2017-08-30 at 10 24 56 am](https://user-images.githubusercontent.com/1912864/29856064-0d328600-8d6e-11e7-9931-15f0f4a015db.png)



_If you are really interested in contributing to open source then contact me on `anil@joshsoftware.com`_
