### ISSUE TITLE
Query Please

### ISSUE THREAD

**Issue by raghavdubey** [joshsoftware/code-curiosity#346]
Can anyone please tell me that on codecuriosity , What is meant by Royalty Point?

**Comment by prasadsurase** [comment]
@raghavdubey royalty points are the bonus points a user gets when he joins Code Curiosity. They points are calculated for contributions to his repositories which have more than 25 stars. Please read the [FAQs](https://codecuriosity.org/faq).

**Comment by raghavdubey** [comment]
Thank you mate
