### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mishraanmol** [joshsoftware/code-curiosity#347]
On my profile , I am seeing under my profile that there is 0 point award to me for August whereas the graph reflects that I have got point, Similar think is happening with my activities section, it is showing 17 activities in my profile graph whereas 0 activities in my contribution section, please help me out @gautamrege

**Comment by amitk** [comment]
@mishraanmol your points are added to your profile at the end of the round. Please read the [FAQs](https://codecuriosity.org/faq)

**Comment by mishraanmol** [comment]
Thank you @amitk for info
It was really helpful
