### ISSUE TITLE
Github gift card not received after (at least) a three weeks

### ISSUE THREAD

**Issue by redfast00** [joshsoftware/code-curiosity#357]

**Comment by amitk** [comment]
@redfast00 We have received your redeem request and It is under process.

**Comment by Roshanjossey** [comment]
@redfast00, have you received gift card now? If yes can you come back and confirm here?

I also have a redemption request I submitted on Aug 9 but haven't received anything.

@amitk: Could you tell us how much time it generally takes for processing?

**Comment by wyhaines** [comment]
Closing.
