### ISSUE TITLE
Hyperlink Issue/PR in message when prefix with '#' under contributions 

### ISSUE THREAD

**Issue by budhrg** [joshsoftware/code-curiosity#371]
It would be great there is a hyperlink to respective issue or PR in message when issue number prefix with `#` under contributions page.

See below.
![screenshot from 2017-09-29 21-53-39](https://user-images.githubusercontent.com/1132451/31025700-2cd366cc-a561-11e7-8c1b-cdf13ce8f3ad.png)

**Comment by amitk** [comment]
@budhrg We already have a link to view any contribution on the extreme right of our contributions table.

**Comment by pain11** [comment]
we already provided a link to view your contributions. so, we are closing this issue.
