### ISSUE TITLE
Subscribe is always seen active on left panel

### ISSUE THREAD

**Issue by budhrg** [joshsoftware/code-curiosity#372]
![screenshot from 2017-09-29 21-57-40](https://user-images.githubusercontent.com/1132451/31027295-52f9d128-a567-11e7-8028-977fdc332da3.png)

Even clicking on other links like `Dashboard`, `Goals` etc Subscribe link is visible active.

**Comment by Roshanjossey** [comment]
I don't think this is a bug. This is one way of showing new features of the app.

**Comment by budhrg** [comment]
> I don't think this is a bug. This is one way of showing new features of the app.

It's a weird way IMO  :smile: . The new features can be better shown with some notification banner on top of page where if clicked will be redirected to another page which has full description of the new feature.

**Comment by pain11** [comment]
@budhrg agreed. Made necessary changes.
