### ISSUE TITLE
Commits done close to the end of month are not scored

### ISSUE THREAD

**Issue by tcNickolas** [joshsoftware/code-curiosity#373]
I've done several contributions on September 29 and 30 which have been showing as "In Review" until the end of September. Once the month ended, only the points for earlier contributions were added to my total points (5 for commits and 4 for activities), but the points for latest commits seem to be lost (I think it's highly unlikely that all 6 commits scored 0 points). I've made an effort to meet my goal for September, so it would be really nice to see those commits scored.

![codecuriosity-september2017](https://user-images.githubusercontent.com/10113024/31056887-14ae3c06-a68e-11e7-9375-2f11705ecd77.png)

**Comment by tcNickolas** [comment]
The commits from the end of the month have shown up neither in points for September nor in the current period. 

It looks like contributions are scored with a delay, the points for the month are awarded immediately upon the end of the month, and not re-calculated afterwards. As a suggestion, it makes sense
* either to delay the calculation of the month award for a day or two until all contributions are scored
* or to roll over the points for contributions which were not included in the month award to the next month.

**Comment by wyhaines** [comment]
Closing. I believe that contributions should be queued for scoring when they are done, now, based on a previously closed ticket.
