### ISSUE TITLE
Regarding commits not getting synced

### ISSUE THREAD

**Issue by jaykay12** [joshsoftware/code-curiosity#378]
CodeCuriosity is monitoring all my activities like Comments & Issue Opening & these are being added in a perfect manner but none of my commits made to these repositories are added yet.
Moreover, Both these repositories are having stars more than 1k, so definitely the commits satisfy the minimum criteria.
Kindly see to this issue of mine.

Repo: https://github.com/rg3/youtube-dl
Repo: https://github.com/sotayamashita/awesome-css

**Comment by budhrg** [comment]
I am facing similar issues.

![screenshot from 2017-12-11 14-03-54](https://user-images.githubusercontent.com/1132451/33822140-87ed7b34-de7c-11e7-9869-173140619e5a.png)

**Comment by budhrg** [comment]
Syncing of contributions stops since 9th December now.

/cc @gautamrege @sethu Any issues?

**Comment by amitk** [comment]
@jaykay12 currently all your commits are synced with CodeCuriosity which are made in the repositories you mentioned.
@budhrg all your recent commits are synced with CodeCuriosity.

**Comment by budhrg** [comment]
Thanks @amitk

**Comment by rmm5t** [comment]
**[@gautamrege pointed me here](https://twitter.com/gautamrege/status/954512080857481216)**.

I am also missing a ton of commits. It seems they just don’t sync at all unless you commit directly to the master branch in the first go and to a repository that you don't directly own. i.e. Merged pull-requests don't get sync'd and neither do commits to owned repositories (with over 25 stars) that I personally own.

**Note these January contributions (15 commits) in these repositories (they are all missing in Code Curiosity):**

* https://github.com/coinbase/gdax-node/commits?author=rmm5t (477 ★)
* https://github.com/muan/emojilib/commits?author=rmm5t (736 ★)
* https://github.com/remy/mit-license/commits?author=rmm5t (1661 ★)
* https://github.com/rkneufeld/alfred-emoji-characters-workflow/commits?author=rmm5t (26 ★)
* https://github.com/rmm5t/jquery-timeago/commits?author=rmm5t (3711 ★)
* https://github.com/rmm5t/minitest-matchers_vaccine/commits?author=rmm5t (26 ★)
* https://github.com/rmm5t/jquery-flexselect/commits?author=rmm5t (223 ★)
* https://github.com/rmm5t/liquidmetal/commits?author=rmm5t (258 ★)
* https://github.com/rmm5t/googleapis-mirror/commits?author=rmm5t (40 ★)
* https://github.com/rmm5t/strip_attributes/commits?author=rmm5t (246 ★)
* https://github.com/rmm5t/dotfiles/commits?author=rmm5t (282 ★)

**Also, the 25 star minimum is quite arbitrary. I understand the need for it, but 10 stars would accomplish the same goal. For example, all this good work (46 commits) on a new project that's rapidly gaining traction is lost:**

* https://github.com/jsumners/alfred-emoji/commits?author=rmm5t (18 ★)

**Comment by gautamrege** [comment]
Hi Ryan,
 Thanks for this. @amitk is looking into this.

Regards,
Gautam

**Comment by amitk** [comment]
@rmm5t I am on it will let you know when your problem of your commits not getting sync is resolved.

**Comment by amitk** [comment]
@rmm5t your all commits and activities are now synced with CodeCuriosity.

**Comment by nixmaniack** [comment]
@amitk Commit sync issue again? Seems it has stopped for me since last week.

**Comment by rmm5t** [comment]
Thanks @amitk, but why is the problem happening in the first place? It feels like everything behind the scenes is quite manual. Is that true?

**Comment by amitk** [comment]
@rmm5t sometimes we need to do it manually because GitHub has a limit on no. of requests one client can make and while performing all jobs every day, also involving the repository syncing per user causes, the rate limit to exceed, and it fails to sync repositories.

**Comment by rmm5t** [comment]
@amitk Ah. Thanks for the explanation. That would explain why it seems like a manual "Sync Contributions" button press is always necessary to see new activities, but it doesn't explain why activities always manually sync when I push that button, but commits seemingly do not.

**Comment by gautamrege** [comment]
We're trying to get server white listed with GitHub but it's still wip.

**Comment by kira0204** [comment]
Hi, it would be great if you could link my commits as well :)

**Comment by kira0204** [comment]
@gautamrege, @amitk Still waiting for it :)

**Comment by pain11** [comment]
Issue has been resolved.
