### ISSUE TITLE
The graph data and the data on the blocks seems to be different

### ISSUE THREAD

**Issue by coderhs** [joshsoftware/code-curiosity#381]
<img width="1083" alt="screenshot 2017-10-26 17 16 41" src="https://user-images.githubusercontent.com/979321/32082624-bce52f8c-ba71-11e7-8738-ebc24cd81da5.png">

The point is displayed as 18, but on the graph its 35. The order might be wrong, but the block has a 37 there is no 37 in the graph.

**Comment by anuj-verma** [comment]
Hi @coderhs,
The scores shown on dashboard are total points/commits/activities which you have obtained till last round.
So till last round i.e Sep 2017 you have a total of
* 18 points
* 28 commits
* 37 activities

In current system, `scores of current round are added to your total scores at the end of round`.

The contribution trend graph is showing scores obtained in each round. Your scores of current round i.e Oct 2017 will be added to your total points at the end of round.

**Comment by coderhs** [comment]
@anuj-verma when I hover the graph it says I have 35 points. 25 commit and 18 activities. Sorry that its not clear in my screenshot.

**Comment by coderhs** [comment]
Gotcha. In that case then the issue is that it wasn't clear upfront.
