### ISSUE TITLE
Activities or points for feb month is not visible on dashboard

### ISSUE THREAD

**Issue by narendra36** [joshsoftware/code-curiosity#390]
My profile page link is https://codecuriosity.org/users/narendra36

I have contributed to some organizations having stars over 500, some of them got merged. But the contributions are not reflected on my dashboard page of codecuriosity. What could be the problem ?

**Comment by narendra36** [comment]
My activities also for feb month is updated at the end of feb but still all activities are in review. Points for feb is not updated please look into it. @pratik14 @pain11

**Comment by pain11** [comment]
@narendra36 points for a month of February are updated.
