### ISSUE TITLE
Activities for the month of february not reflected

### ISSUE THREAD

**Issue by saurabh0402** [joshsoftware/code-curiosity#391]
None of my activity for the month of february are reflected on my codecuriosity account even though I have made a few pull requests on a repo with more than 25 stars. Can you please take a look? @amitk 
My CodeCuriosity profile - [https://codecuriosity.org/users/saurabh0402](https://codecuriosity.org/users/saurabh0402)

**Comment by amitk** [comment]
@saurabh0402 I will look into it.

**Comment by saurabh0402** [comment]
Hey @amitk still waiting on this. My activities are still not visible.

**Comment by amitk** [comment]
Are your march activities visible @saurabh0402

**Comment by saurabh0402** [comment]
@amitk Activities on codecuriosity repo (opening of issue) is visible but not on this repo [https://github.com/appteam-nith/HackOnHills/](https://github.com/appteam-nith/HackOnHills/), even though it has 40 stars.

**Comment by saurabh0402** [comment]
@amitk Still waiting on this.
I believe the problem is with the syncing of this repo [https://github.com/appteam-nith/HackOnHills/](https://github.com/appteam-nith/HackOnHills/). Please, take a look.

**Comment by pratik14** [comment]
hey @saurabh0402 we are looking into this. Yes it related to syncing, we will fix it soon. Thanks for your patience

**Comment by pratik14** [comment]
@saurabh0402 points for the month of feb have been updated

**Comment by saurabh0402** [comment]
@pratik14 Thanks.

**Comment by narendra36** [comment]
Hi @pratik14 My activities also for feb month is updated at the end of feb but still all activities are in review. Points for feb is not updated please look into it. #390

**Comment by pain11** [comment]
@narendra36 we are closing this issue now. we will follow your issue on #390
