### ISSUE TITLE
Progress Chart - review performance over time

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#4]
This chart should be **publicly visible without authentication** 

Drop-down options: "Team commits", "Team scores". Each stacked column has the team split

Use column stacked chart: http://www.highcharts.com/demo/column-stacked
Here is the sample image and the [JSFiddle code](https://jsfiddle.net/707zvsbu/)

![chart-2](https://cloud.githubusercontent.com/assets/61500/10536674/56972636-740a-11e5-9b1d-680faf1f5470.png)

**Comment by kirandc** [comment]
Now graph available publicly. Deployed the changes
