### ISSUE TITLE
Link to the product mug in the goal "Mountaineer" doesn't work

### ISSUE THREAD

**Issue by anshuman73** [joshsoftware/code-curiosity#405]
Hey,

It seems Github has removed the mugs from their store, and hence the link to mug in the goals (in the description of "Mountaineer" doesn't work any longer.

I would have submitted a PR along with this to fix, but I can't  figure out where the data is coming from, it's not hardcoded in the HTML files in the /views, so I assume this requires a change in the prod DB.

**Comment by wyhaines** [comment]
Closing. All of this kind of stuff will have to be looked at before we are live again, anyway.
