### ISSUE TITLE
Three months worth of coupon codes still not credited

### ISSUE THREAD

**Issue by rmm5t** [joshsoftware/code-curiosity#420]
Last month's (April 2018) and this month's (May 2018) redemption points have not yet been credited with my requested Amazon gift care yet.

**Comment by rmm5t** [comment]
Make it 3 months now. June 2018 redemption request also submitted.

**Comment by rmm5t** [comment]
@gautamrege What's the status on these redemption issues? I was a paying subscriber, but I was just forced to cancel, because of the lack of redemptions and lack of customer support here.

**Comment by gautamrege** [comment]
We are changing the play. Current redemption is not working out the way we intended. 


We are coning up with a completely new b strategy soon. 

Please stay tuned. 
- Gautam
Sent from my iPhone

www.joshsoftware.com

**Comment by rmm5t** [comment]
@gautamrege Fair enough, but I would suggest that you refund paying customers for the past three months where their redemptions were ignored.

**Comment by gautamrege** [comment]
Working on that. Nobody loses money - it's just a revamp. 

- Gautam
Sent from my iPhone

www.joshsoftware.com
