### ISSUE TITLE
Repository[emberjs/guides] not listing in "My Repositories" tab

### ISSUE THREAD

**Issue by anilmaurya** [joshsoftware/code-curiosity#43]
I have forked `emberjs/guides` https://github.com/anilmaurya/guides but I don't see this repo on "My Repositories" tab

![screen shot 2016-04-12 at 6 35 44 pm](https://cloud.githubusercontent.com/assets/1912864/14460856/76e82d44-00dd-11e6-81c4-b2ae64121579.png)

**Comment by HashNuke** [comment]
Have the same issue. It's been a few hours since I clicked on sync and I still don't find a few of my repositories.

**Comment by gautamrege** [comment]
While this is indeed a bug - it's worth noting that the repositories that you see will be only the ones that have more than 25 stars OR the origin has more than 25 stars!

**Comment by HashNuke** [comment]
@gautamrege Some more info for debugging. The following repos do have more than 25 stars:

* https://github.com/HashNuke/heroku-buildpack-elixir
* https://github.com/HashNuke/hound

also on one of my organizations, this too has more than 25 https://github.com/asdf-vm/asdf

**Comment by jiren** [comment]
@anilmaurya  Fixed and deploy.

**Comment by anilmaurya** [comment]
@jiren Thank you, its working for me.
