### ISSUE TITLE
Logged in as someone else even in incognito

### ISSUE THREAD

**Issue by HashNuke** [joshsoftware/code-curiosity#46]
I see that I'm logged in as "Anil Kumar Maurya" when I visit http://codecuriosity.org/dashboard. Even in incognito.

![screen shot 2016-04-19 at 8 00 04 pm](https://cloud.githubusercontent.com/assets/84005/14642756/5627ba20-0669-11e6-8cdc-dfb34679fc34.png)

\\cc: @anilmaurya

**Comment by anilmaurya** [comment]
It looks like everyone is login with my account and I am not able to logout as well.

**Comment by HashNuke** [comment]
@anilmaurya Sent a quick PR https://github.com/joshsoftware/code-curiosity/pull/47

**Comment by jiren** [comment]
It was my mistake. Added sing_in statement for testing and by mistake commit it.

**Comment by HashNuke** [comment]
@jiren Fix works now. No worries.

I admit this was a little funny like "Main bhi Anil" :) (on the lines of the "Main bhi Anna" slogan)

**Comment by jiren** [comment]
:)

**Comment by anilmaurya** [comment]
Lol :D
