### ISSUE TITLE
Getting standard error message in dashboard page

### ISSUE THREAD

**Issue by sukhbir-singh** [joshsoftware/code-curiosity#478]
![screenshot_2018-10-11-01-00-42-405_com android chrome](https://user-images.githubusercontent.com/13816752/46761122-5d577f00-ccf1-11e8-8793-03205e1abb50.png)

**Comment by Maxim-Mazurok** [comment]
@pratik14 still getting the same error, can you take a look, please?

**Comment by mzfr** [comment]
I am having the same issue

**Comment by prathamesh-sonpatki** [comment]
Running into same issue

**Comment by wyhaines** [comment]
Closing. Not relevant now.
