### ISSUE TITLE
Has CodeCuriosity stopped tracking the contributions?

### ISSUE THREAD

**Issue by AMR-KELEG** [joshsoftware/code-curiosity#479]
Hi all,

I would like to know whether the site is still tracking the contributions/commits or not?

Thanks,
Amr

**Comment by leovarmak** [comment]
+1

**Comment by wyhaines** [comment]
I am going to close this, as it doesn't have context anymore, but to answer the original question -- yes, Code Curiosity shut down. It is in the process of being revived, however.
