### ISSUE TITLE
Can we please remove all this database of emails 

### ISSUE THREAD

**Issue by saadbinakhlaq** [joshsoftware/code-curiosity#484]
https://github.com/joshsoftware/code-curiosity/blob/9582caea4a19513a21a69ec9b060738b3c601f89/sent_mails

**Comment by jahio** [comment]
@pratik14 Sachin recommended I ping you on this - any reason we can't just nuke that file?

**Comment by jahio** [comment]
@wyhaines had a good idea - search the commit history:

> sent_mails doesn't occur anywhere in the entire git history of the repo. Just delete it. It's in the git history if it should ever be needed.  It can be recovered.

Deleting the file. Sorry it took a while to get back to you @saadbinakhlaq.

**Comment by pratik14** [comment]
@jahio yes please go ahead and make changes, I dont see anywhere it is used.
