### ISSUE TITLE
25 star is not enough

### ISSUE THREAD

**Issue by Mte90** [joshsoftware/code-curiosity#49]
There are many projects on github that don't have 25 stars because maybe they are repo that contain translations or with few star on github but with many download.

**Comment by gautamrege** [comment]
@Mte90 We had to draw the line somewhere for choosing which repositories mean "valuable". So our current logic is either your repository or the origin has at least 25 stars. If we work on number of downloads, it does not give us a sign of popularity or value. 

Ideas are welcome!

**Comment by gautamrege** [comment]
Closing for now.
