### ISSUE TITLE
Now webpack is missing....

### ISSUE THREAD

**Issue by wyhaines** [joshsoftware/code-curiosity#495]
Same issue? Lost it during the upgrades from 14.04 to 20.04?

```
       Compilation failed:
       yarn run v1.22.5
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       
       
       error Command "webpack" not found.
     
```

**Comment by wyhaines** [comment]
Webpack is installed, but the error persists.

**Comment by andrewmcodes** [comment]
> Webpack is installed, but the error persists.

Sorry for the drive by but I happened to notice you have webpacker inside of your Gemfile, but you do not have the Node package installed. 

My guess is it can't find the node webpacker. 

From [Webpacker](https://www.npmjs.com/package/@rails/webpacker):

- `yarn add @rails/webpacker`

You'll need to make sure it has the same version as the gem. Lmk if I can say more.

**Comment by wyhaines** [comment]
Fixed.

Added a line to the deploy.rb to ensure that webpacker is installed from the Rails POV.

**Comment by wyhaines** [comment]
Thanks.  I'll take a second look at it.  I didn't realize that anybody would be watching me as I banged around in the codebase.  :)

We're trying to get this all updated to modern versions of everything so that I can bring Code Curiosity back to life.  I appreciate the drive-by.

**Comment by andrewmcodes** [comment]
@wyhaines I was looking through CodeTriage and you could say that the name piqued my interest 😂
