### ISSUE TITLE
Trends chart is still confusing to people.

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#54]
We need to work out a chart to show the following: 
1. How far is the user from reaching his / her goal for the month! I liked the fitbit charts. 
   ![img_0728](https://cloud.githubusercontent.com/assets/61500/16686055/f3ef018a-452c-11e6-81ab-8ffe65e9da2e.JPG)
2. We need a chart to show how the user fares among all the others in that Goal. Ideas welcome.

**Comment by kirandc** [comment]
can we use http://www.highcharts.com/demo/scatter chart where everyone in the portal is plotted on the graph and we will show the logged in user highlighted.

**Comment by apsc92** [comment]
For showing progress of user in achieving his goal we can use http://www.highcharts.com/demo/gauge-activity.
