### ISSUE TITLE
CodeCuriosity Mailers 

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/code-curiosity#60]
- [x] We need to make them HTML and mobile friendly. 
- [x] We need to manage mail  notifications. We need a profile section allowing users to "disable" notifications to them. 
- [x] Currently, we send out only 1 mail every month - progress mail on 21st mail. We also need to send a mailer on the 4th of the month to people who have over 150 points to inform that they have points they can redeem!
- [ ] Send a mail at the end of the month for users who have a wrong goal set. For example, if you are earning 70 points on an average since you joined CodeCuriosity and  are in the Hiker group, the mail should recommend you to change the group to Mountaineer!

**Comment by prasadsurase** [comment]
A standard css library for emails would be good option. Checkout [Foundation for Emails](http://foundation.zurb.com/emails.html).
