### ISSUE TITLE
Inconsistency in showing featured groups

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#64]
PFA 

When first time accessing 
![feature](https://cloud.githubusercontent.com/assets/280199/17252131/06bee83c-55c9-11e6-8fe0-a6e2e682d526.png)

After Refresh 
![show_feature](https://cloud.githubusercontent.com/assets/280199/17252134/0736d52c-55c9-11e6-8ccf-167cf3856b30.png)

Browser version Chrome: Version 49.0.2623.87 (64-bit)

**Comment by gautamrege** [comment]
This is fixed -- please reopen if issue persists.
