### ISSUE TITLE
Email [Your points for the month of ....] is not clear enough.

### ISSUE THREAD

**Issue by anilmaurya** [joshsoftware/code-curiosity#70]
![screen shot 2016-08-08 at 12 23 03 pm](https://cloud.githubusercontent.com/assets/1912864/17471575/e9489db0-5d62-11e6-8d95-939bcdd43e98.png)

**Email states I have 5 points , I thought I lost all my points because I had around 90 points (**last time I checked my profile on code-curiosity**).**

**I checked my profile on code-curiosity and I don't see 5 point anywhere.**

![screen shot 2016-08-08 at 12 30 54 pm](https://cloud.githubusercontent.com/assets/1912864/17471769/19f38866-5d64-11e6-9019-6f751cfddb22.png)

**Comment by gautamrege** [comment]
Argh! The text should read "You need a 100 points to start redeeming them. You need only 5 more points. Go for it!" Will fix

**Comment by gautamrege** [comment]
Fixed.
