### ISSUE TITLE
Is code curiosity for individual developer?

### ISSUE THREAD

**Issue by budhrg** [joshsoftware/code-curiosity#71]
Hi Folks,

After going through the README of the repo, I got to know that one has to be part of a team (at least three members).

Is code-curiosity not for individual? Does the open source contributors has to be in some team to be participant in this contest? 

Or may be code-curiosity is supporting it and it might be documentation issue.

Could anyone help me to enlighten in this matter?

**Comment by pramodshinde** [comment]
@budhrg 
Code curiosity is for Individual and groups, group can be created by anybody(repository owner, company admin, website owners etc.) those who want to track contributions within group, team concept is removed it was there in first prototype of code curiosity, Its a documentation issue. Now team is replaced by a group and it can have any number of members.

**Comment by sethu** [comment]
Readme is out dated. Individual can participate,  we will update the README.

**Comment by gautamrege** [comment]
Oh man! This is my ticket -- I shall update the README :) Thanks for pointing it out @budhrg

**Comment by budhrg** [comment]
Thanks for the responses :smile:

**Comment by gautamrege** [comment]
Readme has been updated.
