### ISSUE TITLE
No way to see history of how points were awarded last month?

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [joshsoftware/code-curiosity#72]
I want to see my activities and points assigned for last month, I am not able to see it.

https://codecuriosity.org/activities#activities shows only for current month.

**Comment by amoludage** [comment]
@prathamesh-sonpatki you can see your point history on your profile page

See below screenshot -

![screenshot from 2016-08-09 19 17 09](https://cloud.githubusercontent.com/assets/10542896/17518534/e9782dba-5e65-11e6-9f8d-ac46196c0ad1.png)

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki @amoludage For checking activities and commits of previous month just change month from Aug to July.

**Comment by amoludage** [comment]
@Shwetakale :+1:

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale How to do that? No link in UI for that.

**Comment by Shwetakale** [comment]
@pramodshinde From calendar just next to trends.


![codecuriosity](https://cloud.githubusercontent.com/assets/6301532/17518933/81fa91bc-5e67-11e6-94c4-f8ed5452e4a0.png)

**Comment by prathamesh-sonpatki** [comment]
Got it, thanks. Its not very intutive though :smile:
