### ISSUE TITLE
What is the meaning of colors?

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [joshsoftware/code-curiosity#73]
![codecuriosity 2016-08-09 19-34-06](https://cloud.githubusercontent.com/assets/621238/17519226/a9da18b4-5e68-11e6-9b06-b3a4aa1944e1.jpg)

**Comment by budhrg** [comment]
Similar questions I had too :+1:

**Comment by gautamrege** [comment]
ok. I will try to add tooltips for this. 
0 points is 1 grey box.  (ignored)
1 or 2 points is orange (good)
3 and 4 is green (excellent)
5 is dark green  (out-standing)

Darker the colour - better the visual representation of how much you have scored.

**Comment by amitk** [comment]
@prathamesh-sonpatki  now this issue had been resolved so, please close this issue.
