### ISSUE TITLE
Implement style guide based test using rubocop

### ISSUE THREAD

**Issue by coolbrg** [joshsoftware/code-curiosity#75]
[`Rubocop`](https://github.com/bbatsov/rubocop) is a great gem in Ruby for static code ananlyzer. 
Adding it as part of tests would insure that code follow language code standards.  

Any plan to add it in near future?

**Comment by narutosanjiv** [comment]
@budhrg [rubycritic](https://github.com/whitesmith/rubycritic) provide developer code climate like html page for viewing. Attaching screenshot for same. 
![rubycritic](https://cloud.githubusercontent.com/assets/897392/17551307/edb86474-5f16-11e6-905e-2edc65236fba.png)

**Comment by budhrg** [comment]
+1 for rubycritic, 

@narutosanjiv Looks good for RoR application.

**Comment by gautamrege** [comment]
We need to be Language Agnostic. CodeCuriosity supports all languages. So, if we do support static code analysis, this should be via some API access from CodeClimate and the languages they support. Also, we need to plan for a language that does not have static code analysis. 

This is a lot more complex than it looks. Keeping open for now.

**Comment by prathamesh-sonpatki** [comment]
I don't think CoC should worry about code analysis, that is not its job :)

**Comment by budhrg** [comment]
@prathamesh-sonpatki If 'CoC' represent 'Code Curiosity' here then we need to document it too :smile: 

Or am I assuming wrong here.

**Comment by narutosanjiv** [comment]
@prathamesh-sonpatki  @budhrg  I think that we are diverting from topics, here we are talking of code curiosity code which in written in rails, so adding ruby based framework will not going to affect.

**Comment by prathamesh-sonpatki** [comment]
Based on https://github.com/joshsoftware/code-curiosity/issues/75#issuecomment-241386251, I thought we are talking about Code Curiosity showing code analysis for repos :smile:

**Comment by budhrg** [comment]
@narutosanjiv  : I was talking about the static analysis of code curiosity source code only :smile:

**Comment by wyhaines** [comment]
Rubocop would  be great to use on Code Curiosity, but I am closing this for now. It can be revisited after we stabilize a few things.
