### ISSUE TITLE
Profile should be accessible through permalink

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#90]
Currently, I am able to access my profile only through this [https://codecuriosity.org/users/56f671b6b749dd042c000002]. It would be better if we add [https://codecuriosity.org/sivagollapalli] similar to GitHub.

**Comment by gautamrege** [comment]
Profile is accessible via https://codecuriosity.org/users/sivagollapalli

**Comment by sivagollapalli** [comment]
Then why we aren't using [https://codecuriosity.org/users/sivagollapalli] to access my profile ? Still, it shows [https://codecuriosity.org/users/56f671b6b749dd042c000002] .

**Comment by Shwetakale** [comment]
@sivagollapalli @gautamrege This was because ```slug``` was not defined on ```user```. Attahced [PR](https://github.com/joshsoftware/code-curiosity/pull/113) for this.
