### ISSUE TITLE
Contact info missing in README

### ISSUE THREAD

**Issue by budhrg** [joshsoftware/code-curiosity#97]
Hi,

I found that there is no contact information available in README to contact to project maintainers.

I would be expecting to have mailing list, irc channel name or any other medium where one can contact. 
We can mix this info 'contributing section' as [this example](https://github.com/projectatomic/adb-atomic-developer-bundle#interested-in-contributing-to-this-project).

Or is it all communication through github issues only?

**Comment by gautamrege** [comment]
Currently, we would prefer only Github issues - because we have "only 2 hands" to work with 😄 
However, a Slack or IRC channel would be great, once we have more bandwidth. 

Am closing this issue for now. I will add some  Contact Information to the README.
