### ISSUE TITLE
Add Vagrant way to create project dev environment locally

### ISSUE THREAD

**Issue by budhrg** [joshsoftware/code-curiosity#98]
Hi,

We all know the power of [Vagrant](https://www.vagrantup.com/) or check [here for its purpose](https://www.reddit.com/r/rails/comments/1w7sid/whats_the_purpose_of_vagrant/cezgo71).

We can use Vagrant to easily setup the development environment instead of populating local machine.

There is also a Vagrant way available for [Ruby on Rails core development](https://github.com/rails/rails-dev-box) and we can refer it.

**Comment by narutosanjiv** [comment]
@budhrg Docker will be much better & easier to configure for basic dev setup.

**Comment by budhrg** [comment]
@narutosanjiv Ya that could also work. But why not both :wink:

**Comment by narutosanjiv** [comment]
@budhrg I will add docker support for doing development. First, we need to clarify certain points:
   1)  Does docker will be blackbox for developers?. 
   2) Do developers need to know & understand basic docker or developers just going to run some script which build & run docker machine without any prior knowledge of docker & its utilities.

**Comment by budhrg** [comment]
@narutosanjiv 

> 1) Does docker will be blackbox for developers?. 
 
In case docker, I think it should be a blackbox for developers.
Just build the site and run locally. IMO it is very hard to use docker as way to develop site in local machine. Hope you agree with this point. 

2> Do developers need to know & understand basic docker or developers just going to run some script which build & run docker machine without any prior knowledge of docker & its utilities.

We don't want to force developers to learn docker. Most will afraid and run away :) with exception of few who may be interested to learn docker.

Hence, I was proposing for Vagrant approach. While **docker** is good way to quickly build and run your site locally but its pain to use it as development tool.

With Vagrant developer workflow would be:
- `vagrant up` (it will take some time to download box but that is one time)
- `vagrant ssh`
- Now inside VM they can run and easily check logs or do whatever like their local machine
- From host, they can work on code and from inside VM they can manage server, db etc

Hope it make sense.

**Comment by narutosanjiv** [comment]
@budhrg Yeah, it making sense. Docker is definitely easy to run but it has it own learning curve.

**Comment by sethu** [comment]
It is not an huge code with different third party integration. So, need for this atleast now.
